# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            YGZ
tagline:          'Yapay Geri Zekâ'
description:      'Yapay Geri Zekâ'
url:              https://yapaygerizeka.github.io
baseurl:          /

paginate:         50

# Custom vars
gems:             [jekyll-paginate]

kramdown:
  input:          GFM
  hard_wrap:      false

github:
  repo:           https://github.com/yapaygerizeka/yapaygerizeka.github.io.git

# Yazarlar
authors:
  onur:
    name: onur
    display_name: Onur Aslan
    email: onur@onur.im
    web: https://onur.im/
    twitter: oasln
    github: onur 
  Command:
    name: Command
    display_name: Command
    twitter: "0x7000"
    github: "0x7000"
  kandalf:
    name: kandalf
    display_name: Furkan Kalkan
    email: furkan.kalkan3@gmail.com
    web: http://furkankalkan.com
    twitter: furkan_kalkan1
    github: geekdinazor
  ob1mod:
    name : ob1mod
    display_name : Samet Sazak
    email: smtszk@gmail.com
    twitter: ob1mod 
    github: geekdinazor 
  Mertcan:
    name: Mertcan
    display_name: Mertcan
    email: admin@mertcangokgoz.com
    web: https://mertcangokgoz.com/
    twitter: 0x2e88ce4
    github: MertcanGokgoz 
